---
apiVersion: batch/v1
kind: Job
metadata:
  name: anticompositebot.harvcheck
  namespace: tool-anticompositebot
  labels:
    name: anticompositebot.harvcheck
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  template:
    metadata:
      labels:
        name: anticompositebot.harvcheck
        toolforge: tool
    spec:
      containers:
        - name: harvcheck
          image: docker-registry.tools.wmflabs.org/toolforge-python37-sssd-base:latest
          command: [ "/data/project/anticompositebot/AntiCompositeBot/harvcheck_start.sh", "job"]
          workingDir: /data/project/anticompositebot
          env:
            - name: HOME
              value: /data/project/anticompositebot
          imagePullPolicy: Always
      restartPolicy: Never
