apiVersion: batch/v1
kind: CronJob
metadata:
  name: anticompositebot.nolicense-cron
  labels:
    name: anticompositebot.nolicense-cron
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: nolicense-cron
            image: docker-registry.tools.wmflabs.org/toolforge-python39-sssd-base:latest
            command: [
              "/data/project/anticompositebot/AntiCompositeBot/venv/bin/python3",
              "/data/project/anticompositebot/AntiCompositeBot/src/nolicense.py"
            ]
            args: []
            workingDir: /data/project/anticompositebot
            env:
            - name: HOME
              value: /data/project/anticompositebot
            - name: LOG_SMTP
              value: "True"
            imagePullPolicy: Always
          restartPolicy: OnFailure
